const http = require('http');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const { spawn } = require('child_process');

const ROOT = __dirname;
const PORT = process.env.PORT || 8080;
const source = fs.readFileSync(path.join(ROOT,'js','data.js'),'utf8');
const db = vm.runInNewContext(source + '\nseed', {});
const state = JSON.parse(JSON.stringify(db));
const tokens = new Map([
  ['demo-student',{id:'u1',name:'Маша К.',login:'student',role:'student'}],
  ['demo-curator',{id:'c1',name:'Анна Сергеевна',login:'curator',role:'curator'}],
  ['demo-admin',{id:'a1',name:'Администратор',login:'admin',role:'admin'}]
]);
let nextId = 1000;

function send(res,status,data,headers={}){const body=data===null?'':JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8',...headers});res.end(body)}
function error(res,status,code,message){send(res,status,{error:{code,message}})}
function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;return tokens.get(h.slice(7))||null}
function role(req,res,roles){const u=auth(req);if(!u){error(res,401,'unauthorized','Нет токена / токен истёк');return null}if(!roles.includes(u.role)){error(res,403,'forbidden','Роль не подходит');return null}return u}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>2e6)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}
function course(id){return state.courses.find(c=>String(c.id)===String(id))}
function steps(c){return (c?.modules||[]).flatMap(m=>m.steps)}
function step(id){for(const c of state.courses){const s=steps(c).find(x=>String(x.id)===String(id));if(s)return {s,c}}return null}
function safeStudentStep(s){const x=JSON.parse(JSON.stringify(s));delete x.solution;delete x.criteria;delete x.check;return x}
function visibleCourse(c){const x=JSON.parse(JSON.stringify(c));x.modules=x.modules.map(m=>({...m,steps:m.steps.map(s=>safeStudentStep(s))}));return x}
function parseRoute(url){return new URL(url,'http://localhost')}
function gradeFilter(c,g){return !g || (Number(c.grades.match(/\d+/)?.[0]||0)<=g && Number(c.grades.match(/(\d+)\D*класс?$/)?.[1]||Number(c.grades.match(/\d+/g)?.pop()||0))>=g)}
function runPython(code,input,timeout=1000){return new Promise(resolve=>{const exe=process.platform==='win32'?'python':'python3';const p=spawn(exe,['-I','-S','-c',code],{cwd:ROOT,stdio:['pipe','pipe','pipe'],env:{PATH:process.env.PATH||''}});let out='',err='',done=false;const finish=v=>{if(done)return;done=true;clearTimeout(timer);resolve(v)};p.stdout.on('data',d=>{out+=d.toString();if(out.length>100000)p.kill('SIGKILL')});p.stderr.on('data',d=>err+=d.toString());p.on('error',e=>finish({verdict:'RE',output:'',error:e.message,time_ms:timeout}));p.on('close',(code,signal)=>{if(signal==='SIGKILL')finish({verdict:'TL',output:out,time_ms:timeout});else finish({verdict:code===0?'OK':'RE',output:out.trim(),error:err.trim(),time_ms:Math.max(1,Date.now()-started)})});const started=Date.now();const timer=setTimeout(()=>p.kill('SIGKILL'),timeout);p.stdin.end(input)});
}
async function handle(req,res){
 const u=parseRoute(req.url), p=u.pathname;
 if(req.method==='GET'&&p==='/api/health')return send(res,200,{status:'ok'});
 if(req.method==='POST'&&p==='/api/auth/login'){const b=await body(req);const map={student:'demo-student',curator:'demo-curator',admin:'demo-admin'};if(!map[b.login]||b.password!=='demo123'&&!(b.login==='admin'&&b.password==='admin')&&!(b.login==='curator'&&b.password==='curator')&&!(b.login==='student'&&b.password==='student'))return error(res,401,'unauthorized','Неверный логин или пароль');const token=map[b.login];return send(res,200,{token,user:tokens.get(token)})}
 if(req.method==='GET'&&p==='/api/auth/me'){const x=role(req,res,['student','curator','admin']);if(x)return send(res,200,{user:x})}
 if(req.method==='POST'&&p==='/api/auth/logout')return send(res,204,null);
 if(req.method==='GET'&&p==='/api/catalog'){let items=state.courses.filter(c=>c.published);const q=u.searchParams.get('q')?.toLowerCase();const tool=u.searchParams.get('tool');if(q)items=items.filter(c=>c.title.toLowerCase().includes(q));if(tool)items=items.filter(c=>c.tool.toLowerCase().includes(tool));return send(res,200,{items:items.map(c=>({id:c.id,title:c.title,short_description:c.goal,tool:c.tool.toLowerCase().includes('minecraft')?'minecraft':c.tool.toLowerCase().includes('python')?'python':'scratch',tool_name:c.tool,grades:{from:Number(c.grades.match(/\d+/)?.[0]||1),to:Number(c.grades.match(/\d+/g)?.pop()||9)},volume:c.duration,modules_count:c.modules.length,steps_count:steps(c).length,cover_url:null})),total:items.length})}
 if(req.method==='GET'&&p==='/api/catalog/filters')return send(res,200,{tools:[{id:'scratch',name:'Scratch',count:1},{id:'minecraft',name:'Minecraft Education',count:1},{id:'python',name:'Python',count:1}],grades:[2,3,4,5,6,7,8,9]});
 let m;
 if(req.method==='GET'&&(m=p.match(/^\/api\/courses\/([^/]+)$/))){const c=course(m[1]);if(!c)return error(res,404,'not_found','Курс не найден');return send(res,200,visibleCourse(c))}
 if(req.method==='GET'&&p==='/api/me/courses'){const x=role(req,res,['student']);if(!x)return;const student=state.students.find(s=>s.id===x.id);return send(res,200,(student?.courses||[]).map(cid=>{const c=course(cid),ss=steps(c),done=ss.filter(s=>s.status==='done').length;return {course:{id:c.id,title:c.title,tool:c.tool},progress:{done,total:ss.length,percent:ss.length?Math.round(done/ss.length*100):0},score:{value:done,max:ss.length},next_step:ss.find(s=>s.status!=='done')||null,pending_count:ss.filter(s=>s.status==='review').length,returned_count:ss.filter(s=>s.status==='returned').length,curator:{id:'c1',name:'Анна Сергеевна'},last_activity_at:new Date().toISOString()}}))}
 if(req.method==='GET'&&(m=p.match(/^\/api\/steps\/([^/]+)$/))){const z=step(m[1]);if(!z)return error(res,404,'not_found','Шаг не найден');const x=auth(req);const s=safeStudentStep(z.s);return send(res,200,{...s,content:s.content||{},submit:s.submit||null,breadcrumbs:{course:{id:z.c.id,title:z.c.title},module:z.c.modules.find(mm=>mm.steps.some(ss=>ss.id===z.s.id))},status:z.s.status||'not_started',prev_step_id:null,next_step_id:null,last_submission:null})}
 if(req.method==='POST'&&(m=p.match(/^\/api\/steps\/([^/]+)\/submissions$/))){const x=role(req,res,['student']);if(!x)return;const z=step(m[1]);if(!z)return error(res,404,'not_found','Шаг не найден');const b=await body(req), s=z.s;const manual=s.check?.includes('Ручная')||/Ручная/.test(s.check||'');let status='passed',score=s.type==='Проект'?5:s.type==='Теория'?1:3,feedback=null,tests=null;if(manual){status='pending';score=null;state.reviews.unshift({id:'r'+(++nextId),student:x.name,studentId:x.id,course:z.c.id,stepId:s.id,step:s.title,type:s.type,age:'только что',status:'ЖДЁТ',comment:''});s.status='review'}else if(s.type==='Задача с тестами'){const code=b.answer?.code||'';const cases=s.tests||[{input:'2 3',output:'5'},{input:'-5 7',output:'2'}];tests=[];for(let i=0;i<cases.length;i++){const t=cases[i],r=await runPython(code,t.input,1000);const ok=r.verdict==='OK'&&r.output.trim()===String(t.output).trim();tests.push({n:i+1,verdict:ok?'OK':r.verdict==='TL'?'TL':'WA',visible:i<2,input:i<2?t.input:undefined,expected:i<2?t.output:undefined,output:i<2?r.output:undefined,time_ms:r.time_ms});if(!ok){status='failed';score=0;break}}}else if(s.answer!==undefined&&b.answer){const given=Object.values(b.answer)[0];if(String(given)!==String(s.answer)){status='failed';score=0;feedback='Попробуй ещё раз.'}}s.status=status==='passed'?'done':status==='failed'?'failed':s.status;return send(res,201,{id:++nextId,step_id:s.id,attempt:1,status,score,max_score:score===null?3:score,check_source:manual?'curator':'auto',answer:b.answer||{},feedback,hint:null,tests,created_at:new Date().toISOString(),reviewed_at:manual?null:new Date().toISOString(),reviewer:null})}
 if(req.method==='GET'&&p==='/api/me/submissions'){const x=role(req,res,['student']);if(!x)return;const items=[];state.courses.forEach(c=>steps(c).forEach(s=>{if(s.status&&s.status!=='idle')items.push({submission:{id:++nextId,status:s.status==='done'?'passed':s.status==='review'?'pending':s.status,score:null,feedback:s.comment||null,created_at:new Date().toISOString()},step:{id:s.id,title:s.title,type:s.type},course:{id:c.id,title:c.title}})}));return send(res,200,{items,total:items.length})}
 if(req.method==='GET'&&p==='/api/curator/queue'){const x=role(req,res,['curator','admin']);if(!x)return;return send(res,200,state.reviews.filter(r=>r.status==='ЖДЁТ').map(r=>({submission_id:r.id,student:{id:r.studentId,name:r.student},course:{id:r.course,title:course(r.course)?.title},step:{id:r.stepId,title:r.step,type:r.type},attempt:1,submitted_at:new Date().toISOString(),waiting_hours:1})))}
 if(req.method==='POST'&&(m=p.match(/^\/api\/curator\/submissions\/([^/]+)\/review$/))){const x=role(req,res,['curator','admin']);if(!x)return;const r=state.reviews.find(r=>r.id===m[1]);if(!r)return error(res,404,'not_found','Работа не найдена');const b=await body(req);if(b.decision==='return'&&!b.comment)return error(res,400,'bad_request','Комментарий обязателен');r.status=b.decision==='accept'?'ПРИНЯТА':'ВОЗВРАЩЕНА';r.comment=b.comment||'';const z=step(r.course,r.stepId);if(z)z.s.status=b.decision==='accept'?'done':'returned';return send(res,200,{submission:{id:r.id,status:b.decision==='accept'?'passed':'returned',score:b.decision==='accept'?b.score||3:null,feedback:r.comment}})}
 if(req.method==='GET'&&p==='/api/admin/step-types'){const x=role(req,res,['admin']);if(!x)return;return send(res,200,[{type:'theory',title:'Теория',check_modes:['none'],content_fields:['body_md']},{type:'quiz',title:'Контрольный вопрос',check_modes:['auto'],content_fields:['question_md','options'],check_fields:['answer_kind','correct','hint']},{type:'scratch',title:'Scratch',check_modes:['auto','manual'],content_fields:['body_md','program','task_md']},{type:'minecraft',title:'Minecraft Education',check_modes:['manual'],content_fields:['world_md','program','task_md','blocks_md']},{type:'code',title:'Задача с тестами',check_modes:['auto'],content_fields:['statement_md','input_md','output_md','limits'],check_fields:['tests','reference_solution']},{type:'project',title:'Проект',check_modes:['manual'],content_fields:['body_md','requirements','hints_md']}])}
 if(req.method==='GET'&&p==='/api/admin/courses'){const x=role(req,res,['admin']);if(x)return send(res,200,state.courses)}
 if(req.method==='POST'&&p==='/api/admin/courses'){const x=role(req,res,['admin']);if(!x)return;const b=await body(req);const c={id:'course-'+(++nextId),title:b.title||'Новый курс',grades:`${b.grades?.from||1}–${b.grades?.to||9} класс`,duration:b.volume||'',tool:b.tool_name||b.tool||'',goal:b.goal||'',published:false,modules:[]};state.courses.push(c);return send(res,201,c)}
 if(req.method==='POST'&&p.match(/^\/api\/admin\/courses\/[^/]+\/modules$/)){const x=role(req,res,['admin']);if(!x)return;const cid=p.split('/')[4],c=course(cid);if(!c)return error(res,404,'not_found','Курс не найден');const b=await body(req),m={id:'m'+(++nextId),title:b.title||'Новый модуль',steps:[]};c.modules.push(m);return send(res,201,m)}
 if(req.method==='POST'&&p==='/api/admin/enrollments'){const x=role(req,res,['admin']);if(!x)return;const b=await body(req);for(const sid of b.student_ids||[])state.assignments.push({student:sid,course:b.course_id,curator:b.curator_id});return send(res,201,{ok:true})}
 return error(res,404,'not_found','Маршрут не найден');
}
const server=http.createServer((req,res)=>{if(req.url.startsWith('/api/')){handle(req,res).catch(e=>error(res,400,'bad_request',e.message));return}let file=path.join(ROOT,req.url==='/'?'index.html':req.url);if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return error(res,404,'not_found','Файл не найден');const ext=path.extname(file);const ct={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.md':'text/markdown; charset=utf-8'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':ct});fs.createReadStream(file).pipe(res)});
server.listen(PORT,()=>console.log(`Educational platform: http://localhost:${PORT}`));
